# Generated by Django 5.2.8 on 2025-12-16 03:42

import voip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0014_asterisk_realtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsteriskExternalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_host', models.CharField(default=voip.models.ami_host_default, max_length=128, verbose_name='AMI host')),
                ('ami_port', models.PositiveIntegerField(default=voip.models.ami_port_default, verbose_name='AMI port')),
                ('ami_username', models.CharField(default=voip.models.ami_username_default, max_length=128, verbose_name='AMI username')),
                ('ami_secret', models.CharField(blank=True, default=voip.models.ami_secret_default, max_length=255, verbose_name='AMI secret')),
                ('ami_timeout', models.PositiveIntegerField(default=voip.models.ami_connect_timeout_default, verbose_name='AMI timeout, sec')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asterisk (external) settings',
                'verbose_name_plural': 'Asterisk (external) settings',
            },
        ),
        migrations.CreateModel(
            name='AsteriskInternalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ami_host', models.CharField(default=voip.models.ami_host_default, max_length=128, verbose_name='AMI host')),
                ('ami_port', models.PositiveIntegerField(default=voip.models.ami_port_default, verbose_name='AMI port')),
                ('ami_username', models.CharField(default=voip.models.ami_username_default, max_length=128, verbose_name='AMI username')),
                ('ami_secret', models.CharField(blank=True, default=voip.models.ami_secret_default, max_length=255, verbose_name='AMI secret')),
                ('ami_timeout', models.PositiveIntegerField(default=voip.models.ami_connect_timeout_default, verbose_name='AMI timeout, sec')),
                ('ami_reconnect', models.PositiveIntegerField(default=voip.models.ami_reconnect_delay_default, verbose_name='AMI reconnect, sec')),
                ('default_context', models.CharField(default='from-internal', max_length=128, verbose_name='Default context')),
                ('external_context', models.CharField(default='from-pstn', max_length=128, verbose_name='External context')),
                ('default_transport', models.CharField(default='transport-udp', max_length=64, verbose_name='Default transport')),
                ('external_ip', models.CharField(blank=True, default='', max_length=64, verbose_name='External IP')),
                ('local_net', models.CharField(default='192.168.0.0/16', max_length=64, verbose_name='Local network')),
                ('codecs', models.CharField(default='ulaw,alaw,gsm,g722,opus', max_length=255, verbose_name='Codecs (comma-separated)')),
                ('auto_provision', models.BooleanField(default=True, verbose_name='Auto provision')),
                ('start_extension', models.PositiveIntegerField(default=1000, verbose_name='Start extension')),
                ('recordings_path', models.CharField(default='/var/spool/asterisk/monitor', max_length=255, verbose_name='Recordings path')),
                ('recording_format', models.CharField(default='wav', max_length=16, verbose_name='Recording format')),
                ('queue_strategy', models.CharField(default='ringall', max_length=32, verbose_name='Queue strategy')),
                ('queue_timeout', models.PositiveIntegerField(default=300, verbose_name='Queue timeout, sec')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asterisk (internal) settings',
                'verbose_name_plural': 'Asterisk (internal) settings',
            },
        ),
        migrations.CreateModel(
            name='ZadarmaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=128, verbose_name='Zadarma key')),
                ('secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Zadarma secret')),
                ('allowed_ip', models.CharField(blank=True, default='185.45.152.42', max_length=64, verbose_name='Allowed IP for webhooks')),
                ('webhook_forward_ip', models.CharField(blank=True, default='', max_length=64, verbose_name='Forwarding proxy IP')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zadarma settings',
                'verbose_name_plural': 'Zadarma settings',
            },
        ),
        migrations.RenameIndex(
            model_name='extension',
            new_name='extensions_context_b55ac4_idx',
            old_name='extensions_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='psaor',
            new_name='ps_aors_id_7318d5_idx',
            old_name='ps_aors_id_idx',
        ),
        migrations.RenameIndex(
            model_name='psauth',
            new_name='ps_auths_id_4aaf76_idx',
            old_name='ps_auths_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pscontact',
            new_name='ps_contacts_id_bda4f3_idx',
            old_name='ps_contacts_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pscontact',
            new_name='ps_contacts_endpoin_493682_idx',
            old_name='ps_contacts_endpoint_idx',
        ),
        migrations.RenameIndex(
            model_name='psendpoint',
            new_name='ps_endpoint_id_2644d1_idx',
            old_name='ps_endpoint_id_idx',
        ),
        migrations.RenameIndex(
            model_name='psidentify',
            new_name='ps_endpoint_id_d5bfac_idx',
            old_name='ps_identify_id_idx',
        ),
        migrations.RenameIndex(
            model_name='psidentify',
            new_name='ps_endpoint_endpoin_676999_idx',
            old_name='ps_identify_endpoint_idx',
        ),
        migrations.RenameIndex(
            model_name='pstransport',
            new_name='ps_transpor_id_0e3b6f_idx',
            old_name='ps_transports_id_idx',
        ),
        migrations.AddField(
            model_name='voipsettings',
            name='forward_unknown_calls',
            field=models.BooleanField(default=False, help_text='Forward webhook payload to external URL when no CRM objects are matched', verbose_name='Forward unknown callers'),
        ),
        migrations.AddField(
            model_name='voipsettings',
            name='forward_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Forward URL'),
        ),
        migrations.AddField(
            model_name='voipsettings',
            name='forwarding_allowed_ip',
            field=models.CharField(blank=True, default='', help_text='Optional: restrict forwarding source IP check (for relayed requests)', max_length=64, verbose_name='Allowed IP for forwarding source'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('Zadarma', 'Zadarma'), ('OnlinePBX', 'OnlinePBX'), ('Asterisk', 'Asterisk')], help_text='Specify VoIP service provider', max_length=100, verbose_name='Provider'),
        ),
    ]
