# Generated by Django 5.2.8 on 2025-12-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0015_asteriskexternalsettings_asteriskinternalsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('zadarma', 'Zadarma'), ('onlinepbx', 'OnlinePBX'), ('asterisk', 'Asterisk')], max_length=32, verbose_name='Provider')),
                ('event_id', models.CharField(help_text='Unique identifier from provider', max_length=128, verbose_name='Event ID (call_id/uuid)')),
                ('event_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Event Type')),
                ('payload', models.JSONField(default=dict, verbose_name='Raw Payload')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'indexes': [models.Index(fields=['provider', 'event_id'], name='voip_webhoo_provide_8a1312_idx'), models.Index(fields=['created_at'], name='voip_webhoo_created_90a292_idx')],
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
