# Generated by Django 5.2.8 on 2025-11-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('crm', '0012_messenger_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIStat',
            fields=[
            ],
            options={
                'verbose_name': 'BI Analytics',
                'verbose_name_plural': 'BI Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.deal',),
        ),
    ]
