# Generated by Django 5.2.8 on 2025-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_client_next_action'),
        ('crm', '0012_messenger_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenueStat',
            fields=[
            ],
            options={
                'verbose_name': 'Forecasts',
                'verbose_name_plural': 'Forecasts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.deal',),
        ),
        migrations.CreateModel(
            name='ForecastsStat',
            fields=[
            ],
            options={
                'verbose_name': 'Forecasts',
                'verbose_name_plural': 'Forecasts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.deal',),
        ),
        migrations.AlterField(
            model_name='clientnextactionforecast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecastpoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nextactionforecast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
