# Generated by Django 5.2.8 on 2025-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userprofile_jssip_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture (max 5MB)', null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar'),
        ),
    ]
