# Generated by Django 5.2.8 on 2025-12-08 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username attempted (stored even if auth failed)', max_length=150, verbose_name='Username')),
                ('auth_type', models.CharField(choices=[('jwt', 'JWT'), ('legacy', 'Legacy Token'), ('session', 'Session')], max_length=20, verbose_name='Authentication Type')),
                ('endpoint', models.CharField(help_text='API endpoint accessed', max_length=255, verbose_name='Endpoint')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP Method')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Authentication Log',
                'verbose_name_plural': 'Authentication Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'auth_type'], name='api_authent_timesta_58d817_idx'), models.Index(fields=['user', '-timestamp'], name='api_authent_user_id_6ba66c_idx'), models.Index(fields=['auth_type', 'success'], name='api_authent_auth_ty_b92b41_idx')],
            },
        ),
    ]
