# Generated by Django 5.2.8 on 2025-11-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('tg', 'Telegram'), ('ig', 'Instagram'), ('call', 'Phone Call'), ('email', 'Email')], default='sms', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('tg', 'Telegram'), ('ig', 'Instagram'), ('email', 'Email')], default='sms', max_length=16)),
                ('locale', models.CharField(blank=True, default='', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variables used in template')),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('size_cache', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('replied', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='marketing.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='marketing.campaignrun')),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.deliverytask')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.messagetemplate'),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField()),
                ('allow_sms', models.BooleanField(default=True)),
                ('allow_tg', models.BooleanField(default=True)),
                ('allow_ig', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=True)),
                ('quiet_hours_from', models.TimeField(blank=True, null=True)),
                ('quiet_hours_to', models.TimeField(blank=True, null=True)),
                ('daily_limit_sms', models.IntegerField(default=5)),
                ('weekly_limit_sms', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.segment'),
        ),
    ]
