# Generated by Django 5.2.8 on 2025-12-10 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_massmailsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_whitelist', models.TextField(blank=True, help_text='One IP address per line. Leave blank to allow all.', verbose_name='IP Whitelist')),
                ('rate_limit', models.PositiveIntegerField(default=60, help_text='Maximum API requests per minute', verbose_name='Rate Limit')),
                ('require_2fa', models.BooleanField(default=False, help_text='Require two-factor authentication for all users', verbose_name='Require 2FA')),
                ('session_timeout', models.PositiveIntegerField(default=60, help_text='Automatic logout after N minutes of inactivity', verbose_name='Session Timeout (minutes)')),
                ('password_min_length', models.PositiveIntegerField(default=8, verbose_name='Password Min Length')),
                ('password_require_uppercase', models.BooleanField(default=True, verbose_name='Require Uppercase')),
                ('password_require_lowercase', models.BooleanField(default=True, verbose_name='Require Lowercase')),
                ('password_require_numbers', models.BooleanField(default=True, verbose_name='Require Numbers')),
                ('password_require_special', models.BooleanField(default=False, verbose_name='Require Special Characters')),
                ('password_expiry_days', models.PositiveIntegerField(default=90, help_text='Set to 0 to disable password expiry', verbose_name='Password Expiry (days)')),
                ('login_attempts_limit', models.PositiveIntegerField(default=5, verbose_name='Login Attempts Limit')),
                ('lockout_duration', models.PositiveIntegerField(default=30, verbose_name='Lockout Duration (minutes)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Company Name')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Company Email')),
                ('company_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Company Phone')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=10, verbose_name='Default Language')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The URL to send webhook POST requests to', verbose_name='URL')),
                ('events', models.JSONField(default=list, help_text='List of events that trigger this webhook', verbose_name='Events')),
                ('secret', models.CharField(help_text='Secret key for HMAC signature verification', max_length=255, verbose_name='Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Success Count')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Failure Count')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255, verbose_name='Name')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='API Key')),
                ('key_hash', models.CharField(help_text='Hashed version of the key for secure storage', max_length=255, verbose_name='Key Hash')),
                ('permissions', models.JSONField(default=list, help_text='List of permission scopes for this key', verbose_name='Permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usage Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_leads', models.BooleanField(default=True, verbose_name='Notify New Leads')),
                ('notify_missed_calls', models.BooleanField(default=True, verbose_name='Notify Missed Calls')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('notify_task_assigned', models.BooleanField(default=True, verbose_name='Notify Task Assigned')),
                ('notify_deal_won', models.BooleanField(default=True, verbose_name='Notify Deal Won')),
                ('notify_message_received', models.BooleanField(default=True, verbose_name='Notify Message Received')),
                ('email_digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='daily', max_length=10, verbose_name='Email Digest Frequency')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('channel_email', models.BooleanField(default=True, verbose_name='Email Channel')),
                ('channel_sms', models.BooleanField(default=False, verbose_name='SMS Channel')),
                ('channel_push', models.BooleanField(default=True, verbose_name='Push Channel')),
                ('channel_telegram', models.BooleanField(default=False, verbose_name='Telegram Channel')),
                ('channel_in_app', models.BooleanField(default=True, verbose_name='In-App Channel')),
                ('user', models.OneToOneField(blank=True, help_text='Leave blank for global settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100, verbose_name='Event')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP Status Code')),
                ('request_body', models.JSONField(verbose_name='Request Body')),
                ('response_body', models.TextField(blank=True, verbose_name='Response Body')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='settings.webhook', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration', models.CharField(help_text='Name of the integration (instagram, facebook, telegram, sms, voip)', max_length=100, verbose_name='Integration')),
                ('action', models.CharField(help_text='Action performed (e.g., message_received, message_sent)', max_length=255, verbose_name='Action')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('request_data', models.JSONField(default=dict, verbose_name='Request Data')),
                ('response_data', models.JSONField(default=dict, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack Trace')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'integration'], name='settings_in_timesta_cd7a41_idx'), models.Index(fields=['status'], name='settings_in_status_02a9fc_idx')],
            },
        ),
    ]
