# Generated by Django 5.2.8 on 2025-12-10 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_new_settings_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook_page_id', models.CharField(max_length=100, unique=True)),
                ('page_name', models.CharField(max_length=255)),
                ('page_category', models.CharField(blank=True, max_length=100)),
                ('access_token', models.TextField(help_text='Facebook Page access token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync_messages', models.BooleanField(default=True, help_text='Automatically sync Messenger messages')),
                ('auto_sync_comments', models.BooleanField(default=True, help_text='Automatically sync post comments')),
                ('auto_sync_posts', models.BooleanField(default=False, help_text='Automatically sync page posts')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
                ('messages_synced', models.IntegerField(default=0)),
                ('comments_synced', models.IntegerField(default=0)),
                ('posts_synced', models.IntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('granted_permissions', models.JSONField(default=list, help_text='List of granted Facebook permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Page',
                'verbose_name_plural': 'Facebook Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_user_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('account_type', models.CharField(default='BUSINESS', max_length=50)),
                ('access_token', models.TextField(help_text='Instagram Graph API access token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=100)),
                ('facebook_page_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync_messages', models.BooleanField(default=True, help_text='Automatically sync Instagram Direct messages')),
                ('auto_sync_comments', models.BooleanField(default=True, help_text='Automatically sync post comments')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255)),
                ('messages_synced', models.IntegerField(default=0)),
                ('comments_synced', models.IntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('media_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_token', models.CharField(help_text='Telegram Bot API token', max_length=100, unique=True)),
                ('bot_username', models.CharField(max_length=100)),
                ('bot_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_reply', models.BooleanField(default=False, help_text='Enable automatic replies')),
                ('webhook_url', models.URLField(blank=True, help_text='Telegram webhook URL for receiving updates')),
                ('webhook_secret_token', models.CharField(blank=True, help_text='Secret token for webhook validation', max_length=255)),
                ('use_webhook', models.BooleanField(default=True, help_text='Use webhook instead of polling')),
                ('messages_received', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('active_chats', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, help_text='Welcome message for new users')),
                ('commands', models.JSONField(default=dict, help_text='Custom bot commands configuration')),
                ('allowed_chat_ids', models.JSONField(blank=True, default=list, help_text='List of allowed Telegram chat IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
                'ordering': ['-created_at'],
            },
        ),
    ]
