# Generated by Django 5.2.8 on 2025-12-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_phone_e164'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Phone (E.164)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_e164',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Mobile (E.164)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Phone (E.164)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile_e164',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Mobile (E.164)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Phone (E.164)'),
        ),
    ]
